batch_size:
  desc: ''
  sort: 3
  value: 256
early_stopping:
  desc: ''
  sort: 5
  value: 1000
epochs:
  desc: ''
  sort: 2
  value: 8000
learning_rate:
  desc: ''
  sort: 4
  value: 1.0e-06
save_model:
  desc: ''
  sort: 6
  value: models/model.ckpt
seed:
  desc: ''
  sort: 0
  value: 5201314
val_ratio:
  desc: ''
  sort: 1
  value: 0.2
